### ISSUE TITLE
401 Unauthorized 

### ISSUE THREAD

**Issue by gaganmurghai** [cvrapidk/docs.rest.cvrapi.dk#10]
Hi,
I am making a curl request as mentioned in the example 
curl http://rest.cvrapi.dk/v1/dk/company/10150817
and getting "401 Unauthorized " everytime.
as mentioned in the doc http://docs.rest.cvrapi.dk/  "You are not forced to use a key to use CVR API"
So how do i get authorisation user or token to access this API or let me know if i need to send some additional parameter along with this API request.

**Comment by raunsbaekdk** [comment]
Hi
What company are you representing?
You will need to fill out the contact form on: http://cvrapi.dk/contact
